modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="darkshape"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="Darkness Shaped"
description='''
A mod based around my novel and the powers of the characters.
'''

[[dependencies.darkshape]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
